services:

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: homeassistant
    expose:
      - "8123"
    environment:
      - TZ='Europe/Madrid'
#      - DISABLE_JEMALLOC=true
    volumes:
      - ./app_config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
